### PR TITLE
tag r3_9_1

### LINKED ISSUE #289: Outdated. Latest version is 3.9.1
Outdated. Latest version is 3.9.1

### PR DESCRIPTION
**Pull request by ranfdev**
supersedes #174 and fixes #289

### CODE REVIEW

**Comment by joao-p-marques** [comment]
Thanks! I'll merge it as it fixes the build, and it shouldn't have much impact on the audio, but we can always revert if it causes some issues

**Comment by ann0see** [comment]
Thank you! So just rename icon is needed.

**Comment by ann0see** [comment]
The audio should work. My PR does at least #300

**Comment by 38github** [comment]
Thank you all so much!

**Pull request merged**
