### PR TITLE
Update platform to 5.15-21.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Review by joao-p-marques — COMMENTED** [review]
Thanks for the contribution 👍 Could you explain a little bit why this is necessary and what changes it will introduce?

**Comment by farribeiro** [comment]
The base runtime behind 5.15 is soon EOL
Base runtime behind 5.15-21.08 has one more year until EOL

And also newer libs

**Comment by hfiguiere** [comment]
5.15 IS already EOL. Flatpak should even give you a warning about that.

**Review by joao-p-marques — APPROVED** [review]
Thanks for the contribution and the explanation

**Comment by farribeiro** [comment]
Link to PR #302

**Pull request merged**
