### PR TITLE
Add Flatpak-data-checker to fetch latest release and auto update

### PR DESCRIPTION
**Pull request by joao-p-marques**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Why not use https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker ?

**Comment by joao-p-marques** [comment]
> Why not use https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker ?

I'd like to integrate it with GH Actions to automatically open a PR with the changes for easier review, for example. However, maybe an improvement to this would be using flatpak-data-checker from the Action, I hadn't thought of that...

**Comment by bilelmoussaoui** [comment]
> > Why not use https://github.com/flathub/flatpak-external-data-checker#anitya-release-monitoring-checker ?
> 
> I'd like to integrate it with GH Actions to automatically open a PR with the changes for easier review, for example. However, maybe an improvement to this would be using flatpak-data-checker from the Action, I hadn't thought of that...

Well the flatpak-data-checker is run by a Github action, it's just set up across the whole flathub org and @flathubbot opens a PR and can automatically merge things as well :)

**Comment by joao-p-marques** [comment]
> Well the flatpak-data-checker is run by a Github action, it's just set up across the whole flathub org and @flathubbot opens a PR and can automatically merge things as well :)

Oh nice :heart_eyes: How can I activate it then? Is it done by default?

**Comment by bilelmoussaoui** [comment]
You just need to modify your manifest and add to each module you want to monitor the checker you want to use. See the link I shared above. The action is run hourly iirc, so you should receive a PR soon after doing the changes here. 

The auto merge is an option you can enable through flathub.json file

**Comment by joao-p-marques** [comment]
Thanks for the pointer @bilelmoussaoui 

I ended up choosing the "git" type, however, as the project is not currently on release-monitoring.org

**Comment by Alexander-Wilms** [comment]
I've added it to release-monitoring.org: https://release-monitoring.org/project/155434/

**Comment by joao-p-marques** [comment]
Thanks @Alexander-Wilms

**Pull request merged**
